slam_toolbox:
  ros__parameters:
    use_sim_time: true
    base_frame: robot_footprint
    odom_frame: odom
    map_frame: map
    scan_topic: /warehouse_robot/scan
    map_update_interval: 1.0
    resolution: 0.05
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    mode: mapping